// F14m1 Edit Requirement Modal — Pattern A scaffold (M3 Day-13 evening).
//
// Locked reference: PM1_UI_v2/Redesign Frame by claude design/F14m1
// Edit Requirement Modal v2.html
//
// Per Hard Rule 15: pixel-faithful port within React-component idioms.
//
// Sizing canon (01_SYSTEM.md §4.4): Edit modal = 960×720 desktop;
// full-screen Drawer < md per Hard Rule 12.f. The locked HTML uses
// 720 px max-w + 90vh max-h — kept verbatim for v2 parity.
//
// Composer ⓘ "Suggest 5 ACs" banner is an AI surface — uses
// `<AgentName code="composer" />` (Hard Rule 15 single source of truth)
// and `var(--secondary)` violet token family.
//
// Pattern A: every interactive site fires a `pattern-a:deferred:f14m1:*`
// console marker. Pattern B (M3 close, Day-16+) wires real
// PATCH /api/projects/:projectId/requirements/:id + the Composer
// streaming endpoint.

'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { Plus, Sparkles, X } from 'lucide-react';
import { AgentName } from '@/components/ui/agent-name';

// ---------------------------------------------------------------------------
// Types — locally typed view models. Pattern B will swap to imports
// from `@qa-nexus/shared` once BE+1 ships the Requirement Zod schemas.
// ---------------------------------------------------------------------------

type Priority = 'P0' | 'P1' | 'P2' | 'P3';
type Status = 'draft' | 'in-review' | 'approved' | 'archived';
type Sprint = '42' | '43' | 'backlog';

interface AcceptanceCriterion {
  id: string;
  text: string;
  /** True if the row was generated by Composer (renders the violet
   *  AI badge). Edited rows keep the badge so the audit trail
   *  remembers the AI provenance. */
  fromComposer?: boolean;
}

interface RequirementDraft {
  id: string; // "RET-247" or "new"
  title: string;
  description: string;
  priority: Priority;
  status: Status;
  sprint: Sprint;
  source: { kind: 'jira' | 'manual'; ref: string };
  acceptanceCriteria: AcceptanceCriterion[];
}

// Demo seed for the editing example (RET-247) per spec.
const SEED_DRAFT: RequirementDraft = {
  id: 'RET-247',
  title: 'Refund window for digital goods extends to 30 days on partial-download failure',
  description:
    'Customer-facing refund window must auto-extend from 14 → 30 days when at least one download segment fails (mid-download corruption, partial CDN response, etc.). Affects refund-eligibility cron + RMA approval matrix; Stock Ops needs a daily reconciliation report.',
  priority: 'P1',
  status: 'in-review',
  sprint: '42',
  source: { kind: 'jira', ref: 'RET-247' },
  acceptanceCriteria: [
    {
      id: 'ac-1',
      text: 'When a digital download fails mid-stream, the eligibility window extends from 14 to 30 days from the original purchase timestamp.',
    },
    {
      id: 'ac-2',
      text: 'Refund-eligibility cron runs every 4 hours and surfaces any auto-extended cases in Stock Ops Lead’s F08 queue with a 30-day SLA.',
    },
    {
      id: 'ac-3',
      text: 'Auto-extended refunds appear in the daily reconciliation report under a separate "partial-download" line item.',
      fromComposer: true,
    },
  ],
};

// Stable seed bank Composer "generates". In Pattern B this comes from
// the LLM gateway; here we ship a small canned list for the visual
// gate.
const COMPOSER_SUGGESTIONS: AcceptanceCriterion[] = [
  {
    id: 'composer-1',
    text: 'Reconciliation report shows partial-download refunds grouped by vendor, with a daily count + total refund value rolled up to the workspace-Admin email digest.',
    fromComposer: true,
  },
  {
    id: 'composer-2',
    text: 'Customer email confirmation says "Refund window extended to 30 days" with the original purchase timestamp + the new expiry timestamp; available in EN/HI locales.',
    fromComposer: true,
  },
  {
    id: 'composer-3',
    text: 'Auto-extension fires only once per order; subsequent failures within the extended window do NOT trigger another extension (idempotency guard).',
    fromComposer: true,
  },
  {
    id: 'composer-4',
    text: 'RMA approval matrix routes auto-extended refunds to the Stock Ops Lead instead of the standard L1 queue, with a "PARTIAL-DL" tag visible in F08.',
    fromComposer: true,
  },
  {
    id: 'composer-5',
    text: 'Audit log entry kb_requirement_window_extended captures: original window (14d), extended window (30d), trigger reason (partial-download | CDN-timeout), and the actor (system).',
    fromComposer: true,
  },
];

// ---------------------------------------------------------------------------
// Main modal component
// ---------------------------------------------------------------------------

interface EditRequirementModalProps {
  /** "RET-247" to edit, "new" for the create flow, null to render
   *  nothing (modal hidden). */
  mode: string | null;
  onClose: () => void;
}

export function EditRequirementModal({ mode, onClose }: EditRequirementModalProps) {
  // Track whether the modal is open. We render nothing when `mode` is
  // null. We seed the draft state from SEED_DRAFT when editing
  // RET-247; in a real app the F14 page would pass the row's data.
  const isOpen = mode !== null;

  // Initial draft per mode. New = blank requirement; edit = seed.
  const initial = useCallback((): RequirementDraft => {
    if (mode === 'new') {
      return {
        id: 'new',
        title: '',
        description: '',
        priority: 'P2',
        status: 'draft',
        sprint: '42',
        source: { kind: 'manual', ref: '' },
        acceptanceCriteria: [],
      };
    }
    // Default: edit RET-247 (Pattern A demo)
    return SEED_DRAFT;
  }, [mode]);

  const [draft, setDraft] = useState<RequirementDraft>(initial);
  const [composerLoading, setComposerLoading] = useState(false);
  const titleInputRef = useRef<HTMLInputElement | null>(null);

  // Reset draft state whenever `mode` changes (closing + reopening).
  useEffect(() => {
    if (isOpen) {
      setDraft(initial());
      setComposerLoading(false);
      console.info('pattern-a:deferred:f14m1:open', { mode });
      // Auto-focus title for accessibility + prompt
      setTimeout(() => titleInputRef.current?.focus(), 80);
    }
  }, [isOpen, initial, mode]);

  // ESC + ⌘+Enter keyboard shortcuts
  useEffect(() => {
    if (!isOpen) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        console.info('pattern-a:deferred:f14m1:keyboard-cancel');
        onClose();
        return;
      }
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
        e.preventDefault();
        console.info('pattern-a:deferred:f14m1:keyboard-save', {
          id: draft.id,
          titleLen: draft.title.length,
        });
        if (draft.title.trim().length > 0) onClose();
      }
    }
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [isOpen, draft.id, draft.title, onClose]);

  // Body scroll-lock while open
  useEffect(() => {
    if (typeof document === 'undefined') return;
    if (isOpen) {
      const prev = document.body.style.overflow;
      document.body.style.overflow = 'hidden';
      return () => {
        document.body.style.overflow = prev;
      };
    }
  }, [isOpen]);

  if (!isOpen) return null;

  // ---------- Pattern A handlers ----------
  function setField<K extends keyof RequirementDraft>(field: K, value: RequirementDraft[K]) {
    console.info(`pattern-a:deferred:f14m1:field-change:${String(field)}`);
    setDraft((d) => ({ ...d, [field]: value }));
  }

  function addAc() {
    console.info('pattern-a:deferred:f14m1:ac-add');
    setDraft((d) => ({
      ...d,
      acceptanceCriteria: [...d.acceptanceCriteria, { id: `ac-${Date.now()}`, text: '' }],
    }));
  }

  function removeAc(id: string) {
    console.info('pattern-a:deferred:f14m1:ac-remove', { id });
    setDraft((d) => ({
      ...d,
      acceptanceCriteria: d.acceptanceCriteria.filter((ac) => ac.id !== id),
    }));
  }

  function editAc(id: string, text: string) {
    setDraft((d) => ({
      ...d,
      acceptanceCriteria: d.acceptanceCriteria.map((ac) => (ac.id === id ? { ...ac, text } : ac)),
    }));
  }

  function suggestAcs() {
    console.info('pattern-a:deferred:f14m1:composer-suggest-acs', {
      titleLen: draft.title.length,
      descLen: draft.description.length,
      existingAcs: draft.acceptanceCriteria.length,
    });
    setComposerLoading(true);
    // Simulate Composer round-trip (~1.4 s)
    setTimeout(() => {
      setDraft((d) => ({
        ...d,
        acceptanceCriteria: [...d.acceptanceCriteria, ...COMPOSER_SUGGESTIONS],
      }));
      setComposerLoading(false);
    }, 1400);
  }

  function handleSave() {
    if (draft.title.trim().length === 0) return;
    console.info('pattern-a:deferred:f14m1:save', {
      id: draft.id,
      title: draft.title.slice(0, 80),
      acCount: draft.acceptanceCriteria.length,
    });
    onClose();
  }

  function handleCancel() {
    console.info('pattern-a:deferred:f14m1:cancel');
    onClose();
  }

  function handleBackdropClick() {
    console.info('pattern-a:deferred:f14m1:backdrop-close');
    onClose();
  }

  const titleEmpty = draft.title.trim().length === 0;

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="f14m1-title"
      className="fixed inset-0 z-50 flex items-stretch justify-center sm:items-center sm:p-4"
      style={{ background: 'rgba(0,0,0,0.6)' }}
      onClick={handleBackdropClick}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        className="flex max-h-screen w-full flex-col overflow-hidden bg-[var(--base)] sm:max-h-[90vh] sm:max-w-[720px] sm:rounded-xl sm:border"
        style={{ borderColor: 'var(--border-subtle)' }}
      >
        {/* ── Header ── */}
        <header
          className="flex items-start justify-between gap-3 border-b px-5 py-4 sm:px-6"
          style={{ borderColor: 'var(--border-subtle)' }}
        >
          <div className="flex min-w-0 flex-col gap-1">
            <span
              className="font-mono text-[10.5px] font-semibold uppercase tracking-[0.08em]"
              style={{ color: 'var(--text-tertiary)' }}
            >
              {mode === 'new' ? 'New requirement' : `Edit requirement · ${draft.id}`}
            </span>
            <h2
              id="f14m1-title"
              className="font-display text-[18px] font-bold leading-[24px] text-[var(--text-primary)] sm:text-[20px] sm:leading-[28px]"
            >
              {mode === 'new' ? 'Create a new requirement' : 'Edit requirement details'}
            </h2>
            <p className="text-[12.5px] leading-[18px] text-[var(--text-tertiary)]">
              Title, description, and acceptance criteria flow into{' '}
              <AgentName code="composer" inherit /> when you generate test cases.
            </p>
          </div>
          <button
            type="button"
            onClick={handleCancel}
            aria-label="Close modal"
            className="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-md text-[var(--text-tertiary)] transition-colors hover:bg-[var(--overlay)] hover:text-[var(--text-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)]"
          >
            <X size={16} aria-hidden="true" />
          </button>
        </header>

        {/* ── Scrollable body ── */}
        <div className="flex-1 overflow-y-auto px-5 py-5 sm:px-6">
          <form
            className="flex flex-col gap-[18px]"
            onSubmit={(e) => {
              e.preventDefault();
              handleSave();
            }}
          >
            {/* Title */}
            <Field label="Title" required htmlFor="f14m1-title-input">
              <input
                id="f14m1-title-input"
                ref={titleInputRef}
                type="text"
                value={draft.title}
                onChange={(e) => setField('title', e.target.value)}
                placeholder="Short, testable, user-facing outcome…"
                className="h-10 w-full rounded-md border bg-[var(--canvas)] px-3 text-[13.5px] text-[var(--text-primary)] placeholder:text-[var(--text-tertiary)] focus:outline-none focus:ring-2"
                style={{
                  borderColor: 'var(--border-subtle)',
                  // @ts-expect-error inline ring color via custom prop
                  '--tw-ring-color': 'rgba(45,212,191,0.50)',
                }}
              />
            </Field>

            {/* Description */}
            <Field label="Description" htmlFor="f14m1-desc">
              <textarea
                id="f14m1-desc"
                rows={4}
                value={draft.description}
                onChange={(e) => setField('description', e.target.value)}
                placeholder="What changes about the customer or operator experience? Why now?"
                className="min-h-[80px] w-full resize-y rounded-md border bg-[var(--canvas)] p-3 text-[13px] leading-[1.5] text-[var(--text-primary)] placeholder:text-[var(--text-tertiary)] focus:outline-none focus:ring-2"
                style={{
                  borderColor: 'var(--border-subtle)',
                  // @ts-expect-error inline ring color
                  '--tw-ring-color': 'rgba(45,212,191,0.50)',
                }}
              />
            </Field>

            {/* Composer suggest-ACs banner */}
            <ComposerBanner
              loading={composerLoading}
              onClick={suggestAcs}
              acCount={draft.acceptanceCriteria.length}
            />

            {/* Acceptance criteria list */}
            <Field label="Acceptance criteria">
              <div className="flex flex-col gap-2">
                {draft.acceptanceCriteria.map((ac, idx) => (
                  <AcRow
                    key={ac.id}
                    index={idx + 1}
                    ac={ac}
                    onChange={(v) => editAc(ac.id, v)}
                    onRemove={() => removeAc(ac.id)}
                  />
                ))}
                <button
                  type="button"
                  onClick={addAc}
                  className="inline-flex h-9 items-center justify-center gap-1.5 rounded-md border border-dashed px-3 text-[12.5px] font-medium text-[var(--text-tertiary)] transition-colors hover:border-[var(--secondary)] hover:text-[var(--text-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)]"
                  style={{ borderColor: 'var(--border-subtle)' }}
                >
                  <Plus size={13} aria-hidden="true" />
                  Add criterion
                </button>
              </div>
            </Field>

            {/* Priority + Status row */}
            <div className="grid grid-cols-1 gap-[18px] sm:grid-cols-2">
              <Field label="Priority" required htmlFor="f14m1-priority">
                <Select
                  id="f14m1-priority"
                  value={draft.priority}
                  onChange={(v) => setField('priority', v as Priority)}
                  options={[
                    { value: 'P0', label: 'P0 — Critical' },
                    { value: 'P1', label: 'P1 — High' },
                    { value: 'P2', label: 'P2 — Medium' },
                    { value: 'P3', label: 'P3 — Low' },
                  ]}
                />
              </Field>
              <Field label="Status" required htmlFor="f14m1-status">
                <Select
                  id="f14m1-status"
                  value={draft.status}
                  onChange={(v) => setField('status', v as Status)}
                  options={[
                    { value: 'draft', label: 'Draft' },
                    { value: 'in-review', label: 'In review' },
                    { value: 'approved', label: 'Approved' },
                    { value: 'archived', label: 'Archived' },
                  ]}
                />
              </Field>
            </div>

            {/* Sprint + Source row */}
            <div className="grid grid-cols-1 gap-[18px] sm:grid-cols-2">
              <Field label="Sprint" required htmlFor="f14m1-sprint">
                <Select
                  id="f14m1-sprint"
                  value={draft.sprint}
                  onChange={(v) => setField('sprint', v as Sprint)}
                  options={[
                    { value: '42', label: 'Sprint 42 (active)' },
                    { value: '43', label: 'Sprint 43' },
                    { value: 'backlog', label: 'Backlog' },
                  ]}
                />
              </Field>
              <Field label="Source" htmlFor="f14m1-source">
                <input
                  id="f14m1-source"
                  type="text"
                  value={draft.source.kind === 'jira' ? `Jira · ${draft.source.ref}` : 'Manual'}
                  readOnly
                  className="h-10 w-full rounded-md border bg-[var(--canvas)] px-3 text-[13px] text-[var(--text-secondary)]"
                  style={{ borderColor: 'var(--border-subtle)' }}
                />
                <span className="mt-1 block text-[11px] text-[var(--text-tertiary)]">
                  Auto-synced from Jira every 15 min.
                </span>
              </Field>
            </div>
          </form>
        </div>

        {/* ── Footer ── */}
        <footer
          className="flex flex-col-reverse items-stretch justify-between gap-2 border-t bg-[var(--base)] px-5 py-3 sm:flex-row sm:items-center sm:px-6"
          style={{ borderColor: 'var(--border-subtle)' }}
        >
          <span className="hidden font-mono text-[11px] text-[var(--text-tertiary)] sm:inline">
            ⌘+Enter to save · Esc to cancel
          </span>
          <div className="flex flex-col-reverse gap-2 sm:flex-row sm:items-center">
            <button
              type="button"
              onClick={handleCancel}
              className="inline-flex h-10 min-h-[44px] items-center justify-center rounded-md border px-4 text-[13px] font-medium text-[var(--text-secondary)] transition-colors hover:bg-[var(--overlay)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)] sm:min-h-0"
              style={{ borderColor: 'var(--border-subtle)' }}
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleSave}
              disabled={titleEmpty}
              className="inline-flex h-10 min-h-[44px] items-center justify-center rounded-md px-4 text-[13px] font-semibold transition-opacity hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)] disabled:cursor-not-allowed disabled:opacity-50 sm:min-h-0"
              style={{ background: 'var(--primary)', color: 'var(--primary-ink)' }}
            >
              Save changes
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function Field({
  label,
  required,
  htmlFor,
  children,
}: {
  label: string;
  required?: boolean;
  htmlFor?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col gap-1.5">
      <label
        htmlFor={htmlFor}
        className="flex items-center gap-1 font-mono text-[10.5px] font-semibold uppercase tracking-[0.08em] text-[var(--text-tertiary)]"
      >
        {label}
        {required && (
          <span aria-hidden="true" style={{ color: 'var(--fail)' }}>
            *
          </span>
        )}
      </label>
      {children}
    </div>
  );
}

function Select({
  id,
  value,
  onChange,
  options,
}: {
  id?: string;
  value: string;
  onChange: (v: string) => void;
  options: { value: string; label: string }[];
}) {
  return (
    <select
      id={id}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      className="h-10 w-full rounded-md border bg-[var(--canvas)] px-3 text-[13px] text-[var(--text-primary)] focus:outline-none focus:ring-2"
      style={{
        borderColor: 'var(--border-subtle)',
        // @ts-expect-error inline ring color
        '--tw-ring-color': 'rgba(45,212,191,0.50)',
      }}
    >
      {options.map((o) => (
        <option key={o.value} value={o.value}>
          {o.label}
        </option>
      ))}
    </select>
  );
}

function ComposerBanner({
  loading,
  onClick,
  acCount,
}: {
  loading: boolean;
  onClick: () => void;
  acCount: number;
}) {
  return (
    <div
      role="region"
      aria-label="Composer suggestion"
      className="flex flex-col items-start gap-3 rounded-lg border p-3 sm:flex-row sm:items-center sm:gap-4"
      style={{
        background: 'rgba(167,139,250,0.10)',
        borderColor: 'rgba(167,139,250,0.30)',
      }}
    >
      <span
        aria-hidden="true"
        className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-md"
        style={{ background: 'rgba(167,139,250,0.20)', color: 'var(--secondary)' }}
      >
        <Sparkles size={16} />
      </span>
      <div className="flex min-w-0 flex-1 flex-col gap-1">
        <p className="text-[13px] font-medium text-[var(--text-primary)]">
          Auto-suggest acceptance criteria with <AgentName code="composer" inherit />
        </p>
        <p className="text-[11.5px] leading-[1.4] text-[var(--text-tertiary)]">
          Reads the title + description above + your project KB, drafts 3-5 testable ACs you can
          accept, edit, or dismiss. Already added: {acCount}.
        </p>
      </div>
      <button
        type="button"
        onClick={onClick}
        disabled={loading}
        className="inline-flex h-9 shrink-0 items-center gap-1.5 rounded-md px-3 text-[12.5px] font-semibold transition-opacity hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)] disabled:opacity-60"
        style={{ background: 'rgba(167,139,250,0.20)', color: 'var(--secondary)' }}
      >
        <Sparkles size={13} aria-hidden="true" />
        {loading ? 'Composer thinking…' : 'Suggest 5 ACs'}
      </button>
    </div>
  );
}

function AcRow({
  index,
  ac,
  onChange,
  onRemove,
}: {
  index: number;
  ac: AcceptanceCriterion;
  onChange: (v: string) => void;
  onRemove: () => void;
}) {
  return (
    <div className="flex items-start gap-2">
      <span
        className="mt-2 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-md font-mono text-[10.5px] font-semibold"
        style={{
          background: 'var(--raised)',
          color: 'var(--text-tertiary)',
        }}
      >
        {index}
      </span>
      <div className="relative flex-1">
        <textarea
          value={ac.text}
          onChange={(e) => onChange(e.target.value)}
          rows={2}
          placeholder="Given… When… Then… (or any clear, testable statement)"
          className="min-h-[44px] w-full resize-y rounded-md border bg-[var(--canvas)] p-2.5 pr-20 text-[12.5px] leading-[1.4] text-[var(--text-primary)] placeholder:text-[var(--text-tertiary)] focus:outline-none focus:ring-2"
          style={{
            borderColor: 'var(--border-subtle)',
            // @ts-expect-error inline ring
            '--tw-ring-color': 'rgba(45,212,191,0.50)',
          }}
        />
        {ac.fromComposer && (
          <span
            aria-label="Generated by Composer"
            className="absolute right-2 top-2 inline-flex items-center gap-1 rounded-[3px] border px-1.5 py-0.5 font-mono text-[9px] font-bold uppercase tracking-[0.06em]"
            style={{
              background: 'rgba(167,139,250,0.18)',
              borderColor: 'rgba(167,139,250,0.30)',
              color: 'var(--secondary)',
            }}
          >
            <Sparkles size={9} aria-hidden="true" />
            Composer
          </span>
        )}
      </div>
      <button
        type="button"
        onClick={onRemove}
        aria-label={`Remove acceptance criterion ${index}`}
        className="mt-1 inline-flex h-9 min-h-[44px] w-9 min-w-[44px] shrink-0 items-center justify-center rounded-md text-[var(--text-tertiary)] transition-colors hover:bg-[var(--overlay)] hover:text-[var(--fail)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)] sm:min-h-0 sm:min-w-0"
      >
        <X size={14} aria-hidden="true" />
      </button>
    </div>
  );
}
