// F14m2 Link Test Case Modal — Pattern A scaffold (M3 Day-13 evening).
//
// Locked reference: PM1_UI_v2/Redesign Frame by claude design/F14m2
// Link Test Case Modal v2.html
//
// Per Hard Rule 15: pixel-faithful port within React-component idioms.
//
// Sizing canon (01_SYSTEM.md §4.4): Picker modal = 720×640 desktop;
// full-screen Drawer < md per Hard Rule 12.f. The locked HTML uses
// 760 px max-w + 90vh max-h — kept verbatim for v2 parity.
//
// Curator ⓘ near-dup hint banner is the signature element — pre-checks
// 2 of 4 Curator-suggested rows on open. Uses `<AgentName code="curator" />`
// (Hard Rule 15 single source of truth) and `var(--secondary)` violet.
// Primary CTA uses `var(--primary-ink)` (#003732) for dark text on
// violet bg — the only ink token in the locked palette.
//
// Pattern A: every interactive site fires `pattern-a:deferred:f14m2:*`.
// Pattern B (M3 close) wires POST /requirements/:id/test-cases.

'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { Search, SlidersHorizontal, Sparkles, X } from 'lucide-react';
import { AgentName } from '@/components/ui/agent-name';

// ---------------------------------------------------------------------------
// Types — locally typed view models. Pattern B will swap to imports
// from `@qa-nexus/shared` once BE+1 ships the TestCase Zod schemas.
// ---------------------------------------------------------------------------

type Priority = 'P0' | 'P1' | 'P2' | 'P3';

interface TestCaseCandidate {
  id: string;
  title: string;
  priority: Priority;
  /** True when this case's title matches Curator's near-dup heuristic
   *  against the requirement we're linking to. Renders the violet
   *  left-stripe + tint + "Curator suggested" tag. */
  curatorSuggested: boolean;
  /** True when the case was originally generated by Composer (separate
   *  badge from Curator suggestion). */
  fromComposer: boolean;
  /** Caption line under the title — e.g. "linked to RET-248" or
   *  "created 2h ago by Composer". */
  meta: string;
}

// Stub data per Iksula Returns canon (TC-RET-0341..0567 per spec)
const STUB_CANDIDATES: TestCaseCandidate[] = [
  {
    id: 'TC-RET-0341',
    title: 'Refund within 14-day window — digital good (paid via UPI)',
    priority: 'P1',
    curatorSuggested: true,
    fromComposer: true,
    meta: 'linked to RET-248',
  },
  {
    id: 'TC-RET-0342',
    title: 'Refund retries 3× with exponential backoff on payment-gateway failure',
    priority: 'P0',
    curatorSuggested: true,
    fromComposer: true,
    meta: 'linked to RET-248',
  },
  {
    id: 'TC-RET-0455',
    title: 'Holiday calendar exceptions (ISE/NSE) freeze the eligibility window',
    priority: 'P2',
    curatorSuggested: true,
    fromComposer: true,
    meta: 'linked to RET-251',
  },
  {
    id: 'TC-RET-0512',
    title: 'PM walkthrough: HDFC + SBI UPI reversal corner cases',
    priority: 'P1',
    curatorSuggested: true,
    fromComposer: false,
    meta: 'linked to RET-248',
  },
  {
    id: 'TC-RET-0523',
    title: '/api/refunds POST with delivery_confirmed_at returns 200 OK + audit row',
    priority: 'P2',
    curatorSuggested: false,
    fromComposer: false,
    meta: 'created 3 days ago by Akshay P.',
  },
  {
    id: 'TC-RET-0541',
    title: 'Refund window timezone calc against IST/PST customer locales',
    priority: 'P3',
    curatorSuggested: false,
    fromComposer: false,
    meta: 'created 1 week ago by Yogesh M.',
  },
  {
    id: 'TC-RET-0567',
    title: '30-day eligibility flips on partial-download failure — happy path',
    priority: 'P1',
    curatorSuggested: false,
    fromComposer: true,
    meta: 'created 2h ago by Composer',
  },
];

// Default-selected: the first 2 Curator-suggested (per spec)
function defaultSelection(): Set<string> {
  return new Set(['TC-RET-0341', 'TC-RET-0342']);
}

// ---------------------------------------------------------------------------
// Token helpers
// ---------------------------------------------------------------------------

function priorityChipStyle(): React.CSSProperties {
  // Neutral overlay bg per spec (priority pills here are quieter than the
  // ones on F14 Requirements list — they're not the row's primary signal).
  return {
    background: 'var(--overlay)',
    color: 'var(--text-secondary)',
  };
}

// ---------------------------------------------------------------------------
// Main modal component
// ---------------------------------------------------------------------------

interface LinkTestCaseModalProps {
  /** The requirement ID we're linking test cases to (e.g. "RET-247").
   *  Null = render nothing. */
  requirementId: string | null;
  onClose: () => void;
}

export function LinkTestCaseModal({ requirementId, onClose }: LinkTestCaseModalProps) {
  const isOpen = requirementId !== null;
  const [selected, setSelected] = useState<Set<string>>(defaultSelection);
  const [search, setSearch] = useState('');
  const [showSuggestedOnly, setShowSuggestedOnly] = useState(false);
  const searchInputRef = useRef<HTMLInputElement | null>(null);

  // Reset on each open + telemetry
  useEffect(() => {
    if (isOpen) {
      setSelected(defaultSelection());
      setSearch('');
      setShowSuggestedOnly(false);
      console.info('pattern-a:deferred:f14m2:open', { requirementId });
      setTimeout(() => searchInputRef.current?.focus(), 80);
    }
  }, [isOpen, requirementId]);

  // ESC closes
  useEffect(() => {
    if (!isOpen) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        console.info('pattern-a:deferred:f14m2:close', { reason: 'esc' });
        onClose();
      }
    }
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [isOpen, onClose]);

  // Body scroll-lock
  useEffect(() => {
    if (typeof document === 'undefined') return;
    if (isOpen) {
      const prev = document.body.style.overflow;
      document.body.style.overflow = 'hidden';
      return () => {
        document.body.style.overflow = prev;
      };
    }
  }, [isOpen]);

  // Filtered list — search + show-suggested toggle
  const visible = useMemo(() => {
    let out = STUB_CANDIDATES;
    if (showSuggestedOnly) out = out.filter((c) => c.curatorSuggested);
    const q = search.trim().toLowerCase();
    if (q.length > 0) {
      out = out.filter((c) => c.id.toLowerCase().includes(q) || c.title.toLowerCase().includes(q));
    }
    return out;
  }, [search, showSuggestedOnly]);

  if (!isOpen) return null;

  const suggestedCount = STUB_CANDIDATES.filter((c) => c.curatorSuggested).length;

  function toggleCase(id: string) {
    const wasSelected = selected.has(id);
    const candidate = STUB_CANDIDATES.find((c) => c.id === id);
    console.info(
      wasSelected ? 'pattern-a:deferred:f14m2:deselect' : 'pattern-a:deferred:f14m2:select',
      { tcId: id, fromSuggested: candidate?.curatorSuggested ?? false },
    );
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function handleLink() {
    if (selected.size === 0) return;
    console.info('pattern-a:deferred:f14m2:link', {
      requirementId,
      tcIds: Array.from(selected),
    });
    onClose();
  }

  function handleClose(reason: 'cancel' | 'backdrop' | 'x') {
    console.info('pattern-a:deferred:f14m2:close', { reason });
    onClose();
  }

  function handleShowSuggested() {
    console.info('pattern-a:deferred:f14m2:curator-show-suggested', { requirementId });
    setShowSuggestedOnly((v) => !v);
  }

  const linkLabel = selected.size === 1 ? 'Link 1 case' : `Link ${selected.size} cases`;

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="f14m2-title"
      className="fixed inset-0 z-50 flex items-stretch justify-center sm:items-center sm:p-4"
      style={{ background: 'rgba(0,0,0,0.6)' }}
      onClick={() => handleClose('backdrop')}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        className="flex max-h-screen w-full flex-col overflow-hidden bg-[var(--base)] sm:max-h-[90vh] sm:max-w-[760px] sm:rounded-xl sm:border"
        style={{ borderColor: 'var(--border-subtle)' }}
      >
        {/* ── Header ── */}
        <header
          className="flex items-start justify-between gap-3 border-b px-5 py-4 sm:px-6"
          style={{ borderColor: 'var(--border-subtle)' }}
        >
          <div className="flex min-w-0 flex-col gap-1">
            <span
              className="font-mono text-[10.5px] font-semibold uppercase tracking-[0.08em]"
              style={{ color: 'var(--info)' }}
            >
              Link test cases · {requirementId}
            </span>
            <h2
              id="f14m2-title"
              className="font-display text-[18px] font-bold leading-[24px] text-[var(--text-primary)] sm:text-[20px] sm:leading-[28px]"
            >
              Link existing test cases to this requirement
            </h2>
            <p
              className="font-mono text-[11.5px] leading-[16px]"
              style={{ color: 'var(--text-tertiary)' }}
            >
              Iksula Returns · 1,284 cases available
            </p>
          </div>
          <button
            type="button"
            onClick={() => handleClose('x')}
            aria-label="Close modal"
            className="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-md text-[var(--text-tertiary)] transition-colors hover:bg-[var(--overlay)] hover:text-[var(--text-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)]"
          >
            <X size={16} aria-hidden="true" />
          </button>
        </header>

        {/* ── Curator near-dup hint banner ── */}
        <div className="px-5 pt-3 sm:px-6">
          <div
            className="flex flex-col items-start gap-2.5 rounded-lg border p-3 sm:flex-row sm:items-center"
            style={{
              background: 'rgba(167,139,250,0.10)',
              borderColor: 'rgba(167,139,250,0.30)',
            }}
          >
            <span
              aria-hidden="true"
              className="inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-md"
              style={{ background: 'rgba(167,139,250,0.20)', color: 'var(--secondary)' }}
            >
              <Sparkles size={13} />
            </span>
            <p className="flex-1 text-[12.5px] leading-[18px] text-[var(--text-primary)]">
              <AgentName code="curator" inherit /> found {suggestedCount} test cases already linked
              to similar requirements (RET-248, RET-251) — you may want to consider these first.
            </p>
            <button
              type="button"
              onClick={handleShowSuggested}
              className="inline-flex h-8 shrink-0 items-center gap-1.5 rounded-md px-3 text-[12px] font-semibold transition-opacity hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)]"
              style={{ background: 'rgba(167,139,250,0.20)', color: 'var(--secondary)' }}
              aria-pressed={showSuggestedOnly}
            >
              {showSuggestedOnly ? 'Show all' : `Show ${suggestedCount} suggested`}
            </button>
          </div>
        </div>

        {/* ── Search row ── */}
        <div
          className="flex items-center gap-2 border-b px-5 py-3 sm:px-6"
          style={{ borderColor: 'var(--border-subtle)' }}
        >
          <label
            className="flex h-9 flex-1 items-center gap-2 rounded-md border bg-[var(--canvas)] px-3 text-[12.5px] text-[var(--text-tertiary)] focus-within:border-[var(--secondary)]"
            style={{ borderColor: 'var(--border-subtle)' }}
          >
            <Search size={13} aria-hidden="true" />
            <input
              ref={searchInputRef}
              type="search"
              value={search}
              onChange={(e) => {
                setSearch(e.target.value);
                console.info('pattern-a:deferred:f14m2:search', { q: e.target.value });
              }}
              placeholder="Search by ID, title, or step text…"
              className="flex-1 bg-transparent text-[var(--text-primary)] placeholder:text-[var(--text-tertiary)] focus:outline-none"
            />
          </label>
          <button
            type="button"
            onClick={() => console.info('pattern-a:deferred:f14m2:filter-open')}
            className="inline-flex h-9 items-center gap-1.5 rounded-md border px-3 text-[12.5px] font-medium text-[var(--text-secondary)] transition-colors hover:bg-[var(--overlay)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)]"
            style={{ borderColor: 'var(--border-subtle)' }}
          >
            <SlidersHorizontal size={13} aria-hidden="true" />
            Filter
          </button>
        </div>

        {/* ── Scrollable case list ── */}
        <div className="flex-1 overflow-y-auto px-3 py-2 sm:px-4">
          <ul className="flex flex-col gap-1.5">
            {visible.map((c) => (
              <CaseRow
                key={c.id}
                candidate={c}
                selected={selected.has(c.id)}
                onToggle={() => toggleCase(c.id)}
              />
            ))}
            {visible.length === 0 && (
              <li
                className="rounded-lg border border-dashed p-6 text-center text-[12.5px] text-[var(--text-tertiary)]"
                style={{ borderColor: 'var(--border-subtle)' }}
              >
                No test cases match your search.
              </li>
            )}
          </ul>
        </div>

        {/* ── Footer ── */}
        <footer
          className="flex flex-col-reverse items-stretch justify-between gap-2 border-t bg-[var(--base)] px-5 py-3 sm:flex-row sm:items-center sm:px-6"
          style={{ borderColor: 'var(--border-subtle)' }}
        >
          <span className="font-mono text-[11px] text-[var(--text-tertiary)]">
            <span className="font-semibold" style={{ color: 'var(--secondary)' }}>
              {selected.size} selected
            </span>
            {' · '}
            {suggestedCount} Curator-suggested
            {' · '}
            {visible.length} visible
          </span>
          <div className="flex flex-col-reverse gap-2 sm:flex-row sm:items-center">
            <button
              type="button"
              onClick={() => handleClose('cancel')}
              className="inline-flex h-10 min-h-[44px] items-center justify-center rounded-md border px-4 text-[13px] font-medium text-[var(--text-secondary)] transition-colors hover:bg-[var(--overlay)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)] sm:min-h-0"
              style={{ borderColor: 'var(--border-subtle)' }}
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleLink}
              disabled={selected.size === 0}
              className="inline-flex h-10 min-h-[44px] items-center justify-center rounded-md px-4 text-[13px] font-semibold transition-opacity hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)] disabled:cursor-not-allowed disabled:opacity-50 sm:min-h-0"
              style={{ background: 'var(--secondary)', color: 'var(--primary-ink)' }}
            >
              {linkLabel}
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// CaseRow — one picker row
// ---------------------------------------------------------------------------

function CaseRow({
  candidate,
  selected,
  onToggle,
}: {
  candidate: TestCaseCandidate;
  selected: boolean;
  onToggle: () => void;
}) {
  const { curatorSuggested } = candidate;
  return (
    <li>
      <button
        type="button"
        onClick={onToggle}
        aria-pressed={selected}
        className="flex w-full items-start gap-3 rounded-lg border-l-[3px] px-3 py-2.5 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--secondary)]"
        style={{
          background: selected
            ? 'rgba(167,139,250,0.10)'
            : curatorSuggested
              ? 'rgba(167,139,250,0.04)'
              : 'transparent',
          borderColor: curatorSuggested ? 'var(--secondary)' : 'transparent',
        }}
      >
        <input
          type="checkbox"
          checked={selected}
          onChange={onToggle}
          onClick={(e) => e.stopPropagation()}
          aria-label={`Select ${candidate.id}`}
          className="mt-0.5 h-4 w-4 cursor-pointer accent-[var(--secondary)]"
        />
        <div className="flex min-w-0 flex-1 flex-col gap-1">
          <span className="font-mono text-[11px] font-semibold" style={{ color: 'var(--primary)' }}>
            {candidate.id}
          </span>
          <span className="text-[13px] leading-[18px] text-[var(--text-primary)]">
            {candidate.title}
          </span>
          <div className="flex flex-wrap items-center gap-1.5 text-[10.5px]">
            <span
              className="inline-flex h-5 items-center rounded-[3px] px-1.5 font-mono font-bold"
              style={priorityChipStyle()}
            >
              {candidate.priority}
            </span>
            {candidate.fromComposer && (
              <span
                className="inline-flex h-5 items-center gap-1 rounded-[3px] border px-1.5 font-mono font-bold uppercase tracking-[0.06em]"
                style={{
                  background: 'rgba(167,139,250,0.10)',
                  borderColor: 'rgba(167,139,250,0.30)',
                  color: 'var(--secondary)',
                }}
              >
                Composer
              </span>
            )}
            {candidate.curatorSuggested && (
              <span
                className="inline-flex h-5 items-center gap-1 rounded-[3px] px-1.5 font-mono font-bold uppercase tracking-[0.06em]"
                style={{ color: 'var(--secondary)' }}
              >
                Curator suggested
              </span>
            )}
            <span
              className="ml-auto truncate text-[var(--text-tertiary)]"
              style={{
                fontFamily: 'var(--font-mono)',
                fontVariantNumeric: 'tabular-nums',
              }}
            >
              {candidate.meta}
            </span>
          </div>
        </div>
      </button>
    </li>
  );
}
