-- =============================================================================
-- QA Nexus PM1 — initial RLS + HNSW + audit-log raw SQL companion
-- =============================================================================
-- Spec:  PM1_ERD §3 + .claude/rules/database.md
-- Task:  MS0-T020 (Day 2)
--
-- This file is the RAW SQL companion to apps/api/prisma/schema.prisma. It
-- handles everything Prisma 5 cannot express:
--
--   1. Enable the pgvector extension (idempotent).
--   2. Row-Level Security policies on every workspace-scoped table, keyed on
--      `current_setting('app.workspace_id')::uuid`. Exemptions per
--      database.md: workspaces, users (top-level), audit_log (admin-only via
--      app guard), and join tables (RLS transitive via parents).
--   3. HNSW indexes on test_cases.embedding + kb_chunks.embedding using
--      vector_cosine_ops with m=16, ef_construction=64.
--   4. audit_log append-only enforcement via REVOKE UPDATE,DELETE on the
--      app role + a trigger that hard-rejects any UPDATE/DELETE.
--
-- This file is NOT generated by `prisma migrate dev` — it must be applied
-- separately, OR converted to a proper Prisma migration once Yogesh
-- provisions Neon and runs `prisma migrate dev --name init`. The Prisma
-- migration will create the tables/columns; this file then layers on the
-- pieces Prisma omits.
--
-- Apply order (when Neon is up):
--   1. `pnpm --filter api prisma migrate dev --name init`   ← Prisma creates tables
--   2. `psql "$DATABASE_URL" -f apps/api/prisma/migrations/0_init_rls_hnsw/migration.sql`
--   OR: copy this file's contents into the generated init migration
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. EXTENSION
-- ─────────────────────────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS vector;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. ROW-LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────────────────────
-- Set `app.workspace_id` per request in NestJS via Prisma `$use` middleware.
-- Never bypass RLS by issuing raw SQL with BYPASSRLS (per database.md).

-- Enable RLS on all workspace-scoped tables.
ALTER TABLE projects                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_members           ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_invitations          ENABLE ROW LEVEL SECURITY;
ALTER TABLE requirements              ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_cases                ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_case_links           ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_suites               ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_suite_members        ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_runs                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_run_results          ENABLE ROW LEVEL SECURITY;
ALTER TABLE jira_connections          ENABLE ROW LEVEL SECURITY;
ALTER TABLE jira_issues               ENABLE ROW LEVEL SECURITY;
ALTER TABLE defects                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE rca_reports               ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb_documents              ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb_chunks                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE llm_providers             ENABLE ROW LEVEL SECURITY;
ALTER TABLE llm_provider_models       ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_model_assignments   ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_runs                ENABLE ROW LEVEL SECURITY;

-- Direct-workspace tables: filter by their own workspace_id.
CREATE POLICY projects_workspace_isolation                ON projects
  USING (workspace_id = current_setting('app.workspace_id')::uuid);

CREATE POLICY user_invitations_workspace_isolation        ON user_invitations
  USING (workspace_id = current_setting('app.workspace_id')::uuid);

CREATE POLICY llm_providers_workspace_isolation           ON llm_providers
  USING (workspace_id = current_setting('app.workspace_id')::uuid);

CREATE POLICY agent_model_assignments_workspace_isolation ON agent_model_assignments
  USING (workspace_id = current_setting('app.workspace_id')::uuid);

CREATE POLICY agent_runs_workspace_isolation              ON agent_runs
  USING (workspace_id = current_setting('app.workspace_id')::uuid);

-- Project-scoped tables: filter by parent project.workspace_id.
CREATE POLICY requirements_workspace_isolation            ON requirements
  USING (EXISTS (SELECT 1 FROM projects p WHERE p.id = requirements.project_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

CREATE POLICY test_cases_workspace_isolation              ON test_cases
  USING (EXISTS (SELECT 1 FROM projects p WHERE p.id = test_cases.project_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

CREATE POLICY test_suites_workspace_isolation             ON test_suites
  USING (EXISTS (SELECT 1 FROM projects p WHERE p.id = test_suites.project_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

CREATE POLICY test_runs_workspace_isolation               ON test_runs
  USING (EXISTS (SELECT 1 FROM projects p WHERE p.id = test_runs.project_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

CREATE POLICY jira_connections_workspace_isolation        ON jira_connections
  USING (EXISTS (SELECT 1 FROM projects p WHERE p.id = jira_connections.project_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

CREATE POLICY defects_workspace_isolation                 ON defects
  USING (EXISTS (SELECT 1 FROM projects p WHERE p.id = defects.project_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

-- kb_documents may have NULL project_id (workspace-scoped). Allow when the
-- document is workspace-scoped (project_id IS NULL is intentional and admin
-- gating is at app layer) OR when the parent project is in the workspace.
CREATE POLICY kb_documents_workspace_isolation            ON kb_documents
  USING (
    project_id IS NULL
    OR EXISTS (SELECT 1 FROM projects p WHERE p.id = kb_documents.project_id
      AND p.workspace_id = current_setting('app.workspace_id')::uuid)
  );

-- Join tables: transitive via parent.
CREATE POLICY project_members_workspace_isolation         ON project_members
  USING (EXISTS (SELECT 1 FROM projects p WHERE p.id = project_members.project_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

CREATE POLICY test_case_links_workspace_isolation         ON test_case_links
  USING (EXISTS (SELECT 1 FROM test_cases tc JOIN projects p ON p.id = tc.project_id
    WHERE tc.id = test_case_links.test_case_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

CREATE POLICY test_suite_members_workspace_isolation      ON test_suite_members
  USING (EXISTS (SELECT 1 FROM test_suites ts JOIN projects p ON p.id = ts.project_id
    WHERE ts.id = test_suite_members.suite_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

CREATE POLICY test_run_results_workspace_isolation        ON test_run_results
  USING (EXISTS (SELECT 1 FROM test_runs tr JOIN projects p ON p.id = tr.project_id
    WHERE tr.id = test_run_results.run_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

CREATE POLICY jira_issues_workspace_isolation             ON jira_issues
  USING (EXISTS (SELECT 1 FROM jira_connections jc JOIN projects p ON p.id = jc.project_id
    WHERE jc.id = jira_issues.jira_connection_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

CREATE POLICY rca_reports_workspace_isolation             ON rca_reports
  USING (EXISTS (SELECT 1 FROM defects d JOIN projects p ON p.id = d.project_id
    WHERE d.id = rca_reports.defect_id
    AND p.workspace_id = current_setting('app.workspace_id')::uuid));

CREATE POLICY kb_chunks_workspace_isolation               ON kb_chunks
  USING (EXISTS (SELECT 1 FROM kb_documents kd
    WHERE kd.id = kb_chunks.document_id
    AND (
      kd.project_id IS NULL
      OR EXISTS (SELECT 1 FROM projects p WHERE p.id = kd.project_id
        AND p.workspace_id = current_setting('app.workspace_id')::uuid)
    )));

CREATE POLICY llm_provider_models_workspace_isolation     ON llm_provider_models
  USING (EXISTS (SELECT 1 FROM llm_providers lp WHERE lp.id = llm_provider_models.provider_id
    AND lp.workspace_id = current_setting('app.workspace_id')::uuid));

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. HNSW INDEXES (vector_cosine_ops, m=16, ef_construction=64)
-- ─────────────────────────────────────────────────────────────────────────────
-- Per database.md. Use CONCURRENTLY in production migrations to avoid lock;
-- omitted here so the statement can run inside a transaction (Prisma default).
-- When applying to Neon, prefer CONCURRENTLY (split into separate non-tx step).

CREATE INDEX test_cases_embedding_hnsw_idx
  ON test_cases USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

CREATE INDEX kb_chunks_embedding_hnsw_idx
  ON kb_chunks USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. audit_log APPEND-ONLY ENFORCEMENT
-- ─────────────────────────────────────────────────────────────────────────────
-- Defence in depth on top of the app-layer rule: no UPDATE, no DELETE, ever.

CREATE OR REPLACE FUNCTION reject_audit_log_mutation()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only — UPDATE/DELETE rejected (op=%, table=%)',
    TG_OP, TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_log_block_update
  BEFORE UPDATE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION reject_audit_log_mutation();

CREATE TRIGGER audit_log_block_delete
  BEFORE DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION reject_audit_log_mutation();

-- Optional: also REVOKE for the app role once the role is created
-- (skipping here because the migration role isn't known until Render/Neon
-- wiring lands in T011/T012). To be added when the app DB role is created:
--
--   REVOKE UPDATE, DELETE ON audit_log FROM app_role;
