// Auto-generated by scripts/extract-canned-data.mjs
// Source HTML: /Users/yogeshmohite/AI_Tester_Project/Project10-QA_Nexus-frontend/QA Nexus/PM1/PM1_UI_v2/Redesign Frame by claude design/F26m2 Agent Model Assignment Modal v2.html
// Frame: F26M2
// Generated: 2026-06-02T13:42:48.605Z
//
// Hard Rule 17 (CLAUDE.md): ALL text content in the React port for this
// frame MUST come from this file. ANY string in a component file that
// doesn't trace back to the v2 HTML is a Hard Rule 17 violation →
// visual gate FAIL.
//
// This file is intended as a STARTING POINT — the FE+1 dev should
// organize these raw extracts into semantically named exports
// (e.g. DEFECT_TITLES, CLUSTER_HEADINGS, RIGHT_RAIL_LABELS) that the
// React port imports from. Re-run this script to refresh extracts; do
// NOT hand-edit the RAW block (it'll be overwritten).

export const F26M2_RAW = {
  pageTitle: 'QA Nexus — F26m2 Configure Composer · Model Assignment',
  headings: {
    h1: [],
    h2: [],
    h3: [],
    h4: [],
    h5: [],
    h6: [],
  },
  dataAttrs: {
    'screen-label': ['F26m2 Configure Composer · Model Assignment'],
  },
  ids: {
    testCaseIds: [],
    defectIds: [],
    requirementIds: ['REQ-088'],
    jiraTicketIds: [],
    importIds: [],
  },
  textByTag: {
    span: [
      'Configure Composer',
      'Per-agent model assignment & routing · Iksula Returns · Admin-only',
      'F26m2',
      'Composer · v2.3',
      '621',
      'Cases generated',
      '98.2%',
      'Accept rate',
      '1.24 s',
      'Avg latency p95',
      '$0.00',
      'Cost today · FREE',
      'Primary model',
      'Required',
      'Used for all generation by default',
      'G',
      'openai/gpt-oss-120b',
      '· Groq',
      'Free',
      '131K ctx',
      '·',
      '500 tok/s',
      '1K RPD',
      'Long-context model',
      'Routing',
      'Used when input exceeds 131K tokens',
      'meta-llama/llama-4-scout-17b-16e-instruct',
      'Preview',
      '10M ctx',
      '300 tok/s',
      'Groq · varies',
      'Fallback model',
      'Used when Primary is rate-limited / down',
      '◆',
      'gemini-2.5-flash',
      '· Google',
      '1M ctx',
      '1.5K RPD',
      'auto-failover',
      'Routing rules',
      'Derived from slots above · read-only',
      '1',
      'By default, all test-case generation routes to Primary',
      '2',
      "If a requirement's context exceeds 131K tokens , the request routes to Long-context",
      '3',
      'If Primary is rate-limited or unavailable, requests auto-failover to Fallback',
      'Test with sample prompt',
      'Dry-run against current routing',
      'Sample prompt · Iksula Returns',
      'REQ-088',
      '8 test cases generated · routed to Primary',
    ],
    div: [
      'Configure Composer — Test Case Generator Per-agent model assignment & routing · Iksula Returns · Admin-only',
      'Composer · v2.3 Active',
      '621 Cases generated',
      '98.2% Accept rate',
      '1.24 s Avg latency p95',
      '$0.00 Cost today · FREE',
      'Primary model Required Used for all generation by default',
      'G openai/gpt-oss-120b · Groq Free',
      '131K ctx · 500 tok/s · 1K RPD',
      'Long-context model Routing Used when input exceeds 131K tokens',
      'G meta-llama/llama-4-scout-17b-16e-instruct Preview',
      '10M ctx · 300 tok/s · Groq · varies',
      'Fallback model Routing Used when Primary is rate-limited / down',
      '◆ gemini-2.5-flash · Google Free',
      '1M ctx · 1.5K RPD · auto-failover',
      'Routing rules Derived from slots above · read-only',
      '1 By default, all test-case generation routes to Primary — gpt-oss-120b on Groq.',
      "2 If a requirement's context exceeds 131K tokens , the request routes to Long-context — llama-4-scout (10M ctx).",
      '3 If Primary is rate-limited or unavailable, requests auto-failover to Fallback — gemini-2.5-flash , then retry Primary next cycle.',
      'Test with sample prompt Dry-run against current routing',
      'Sample prompt · Iksula Returns Generate test cases for REQ-088 : 3D-Secure step-up authentication on checkout for transactions over ₹5,000, including the OTP timeout and fallback-to-PIN paths.',
      'Run sample test 8 test cases generated · routed to Primary · 4.2s · 2,847 tokens · gpt-oss-120b',
      'Model changes write to audit log · Effective immediately for new runs',
      'Cancel Save & activate',
    ],
    p: [],
    li: [],
    a: [],
    button: ['Change', 'Run sample test', 'Cancel', 'Save & activate'],
    label: [],
    td: [],
    th: [],
    small: [],
    em: [],
    strong: [],
    b: ['131K tokens', '8 test cases'],
    i: [],
    code: ['gpt-oss-120b', 'llama-4-scout', 'gemini-2.5-flash'],
  },
  images: {
    alts: [],
    srcs: [],
  },
  ariaAndTitle: {
    arias: ['Close'],
    titles: ['Test Case Generator'],
  },
} as const;

/**
 * Page-level metadata extracted from the canonical v2 HTML <title> +
 * the first <h1>. Always safe to import directly.
 */
export const F26M2_PAGE_TITLE = 'QA Nexus — F26m2 Configure Composer · Model Assignment' as const;

/**
 * Add semantically-named exports below as the React port consumes
 * verbatim text from F26M2_RAW. Examples:
 *
 *   export const F26M2_RIGHT_RAIL_LABELS = F26M2_RAW.textByTag.span.slice(0, 8);
 *   export const F26M2_DEFECT_IDS = F26M2_RAW.ids.defectIds;
 *   export const F26M2_HEADINGS = F26M2_RAW.headings;
 */
