// Auto-generated by scripts/extract-canned-data.mjs
// Source HTML: /Users/yogeshmohite/AI_Tester_Project/Project10-QA_Nexus-frontend/QA Nexus/PM1/PM1_UI_v2/Redesign Frame by claude design/F27m1 Invite User Modal v2.html
// Frame: F27M1
// Generated: 2026-06-06T12:18:44.267Z
//
// Hard Rule 17 (CLAUDE.md): ALL text content in the React port for this
// frame MUST come from this file. ANY string in a component file that
// doesn't trace back to the v2 HTML is a Hard Rule 17 violation →
// visual gate FAIL.
//
// This file is intended as a STARTING POINT — the FE+1 dev should
// organize these raw extracts into semantically named exports
// (e.g. DEFECT_TITLES, CLUSTER_HEADINGS, RIGHT_RAIL_LABELS) that the
// React port imports from. Re-run this script to refresh extracts; do
// NOT hand-edit the RAW block (it'll be overwritten).

 

export const F27M1_RAW = {
  pageTitle: 'QA Nexus — F27m1 Invite to QA Nexus',
  headings: {
    h1: [],
    h2: [],
    h3: [],
    h4: [],
    h5: [],
    h6: [],
  },
  dataAttrs: {
    'screen-label': ['F27m1 Invite to QA Nexus'],
    cfemail: [
      'c7b4a6a9ada6bee9a0b2b7b3a687aeacb4b2aba6e9a4a8aa',
      'ec818989828dc29e8d83ac85879f99808dc28f8381',
      '2b5d4240594a4605454a42596b4240585e474a05484446',
      '7d0e1c13171c04531a080d091c3d14160e08111c531e1210',
      'c0ada5a5aea1eeb2a1af80a9abb3b5aca1eea3afad',
      '7a0c1311081b1754141b13083a1311090f161b54191517',
    ],
  },
  ids: {
    testCaseIds: [],
    defectIds: [],
    requirementIds: [],
    jiraTicketIds: [],
    importIds: ['#39', '#160'],
  },
  textByTag: {
    span: [
      'Invite to QA Nexus',
      'Send invites to join Iksula Services Pvt Ltd — they&#39;ll receive a Resend email with a set-password link.',
      'F27m1',
      'Workspace',
      'Iksula Services Pvt Ltd',
      'Email(s) *',
      'S',
      '[email&#160;protected]',
      'M',
      'V',
      'Apply to all:',
      'Returns',
      'Commerce',
      '+1',
      'Personal message (optional)',
      'Added to the invite email',
      '0 / 500',
      'Resend free tier · 234 / 3,000 emails used this month · ~12 emails/user/month budget',
      'Sending 3 invites · 2 QA Engineers, 1 Lead',
      'Invites expire in 7 days · invitees route to F06b → F07b / F07c / F07d',
      '3',
    ],
    div: [
      'Invite to QA Nexus Send invites to join Iksula Services Pvt Ltd — they&#39;ll receive a Resend email with a set-password link.',
      'Workspace Iksula Services Pvt Ltd',
      'You have 4 of 25 invite slots remaining this month',
      'Email(s) * S [email&#160;protected] M [email&#160;protected] V [email&#160;protected]',
      'Paste multiple emails separated by comma or newline. Max 25 per invite.',
      'Apply to all: QA Engineer Returns, Commerce Apply to all 3 emails',
      'S [email&#160;protected]',
      'Returns',
      'M [email&#160;protected]',
      'Returns Commerce',
      'V [email&#160;protected]',
      'Returns Commerce +1',
      'Personal message (optional) Added to the invite email',
      '0 / 500',
      'Resend free tier · 234 / 3,000 emails used this month · ~12 emails/user/month budget View email metrics →',
      'Sending 3 invites · 2 QA Engineers, 1 Lead Invites expire in 7 days · invitees route to F06b → F07b / F07c / F07d',
      'Cancel Send invites 3',
    ],
    p: [],
    li: [],
    a: ['[email&#160;protected]', 'View email metrics →'],
    button: [
      'QA Engineer',
      'Returns, Commerce',
      'Apply to all 3 emails',
      'QA Lead',
      'Cancel',
      'Send invites 3',
    ],
    label: ['Senior QA', 'N/A'],
    td: [],
    th: [],
    small: [],
    em: [],
    strong: [],
    b: ['4', '25', '234 / 3,000', '3', '2', '1', '7'],
    i: [],
    code: [],
  },
  images: {
    alts: [],
    srcs: [],
  },
  ariaAndTitle: {
    arias: ['Close', 'Remove'],
    titles: [],
  },
} as const;

/**
 * Page-level metadata extracted from the canonical v2 HTML <title> +
 * the first <h1>. Always safe to import directly.
 */
export const F27M1_PAGE_TITLE = 'QA Nexus — F27m1 Invite to QA Nexus' as const;

// F27m1 semantic exports — verbatim from F27m1 Invite User Modal v2.html (Hard Rule 17).

export const F27M1_HEADER = {
  title: 'Invite to QA Nexus' as const,
  subtitle:
    "Send invites to join Iksula Services Pvt Ltd — they'll receive a Resend email with a set-password link." as const,
} as const;

export const F27M1_WORKSPACE = {
  cap: 'Workspace' as const,
  name: 'Iksula Services Pvt Ltd' as const,
  rPrefix: 'You have' as const,
  slotsUsed: 4 as const,
  slotsTotal: 25 as const,
  rSuffix: 'of' as const,
  rTail: 'invite slots remaining this month' as const,
} as const;

export const F27M1_EMAIL = {
  label: 'Email(s)' as const,
  placeholder: 'Type or paste emails…' as const,
  helper: 'Paste multiple emails separated by comma or newline. Max 25 per invite.' as const,
  maxPerInvite: 25 as const,
} as const;

export const F27M1_APPLYALL = {
  cap: 'Apply to all:' as const,
  roleBtn: 'QA Engineer' as const,
  projectsBtn: 'Returns, Commerce' as const,
  // Templated by invitee count
  goLabel: (n: number) => `Apply to all ${n} emails`,
} as const;

// Iksula project catalog — verbatim from CLAUDE.md Iksula data canon.
// Anchor project Returns + 4 others. "Returns" is the Sprint-42 pilot project.
export const F27M1_PROJECTS: ReadonlyArray<{ key: string; label: string }> = [
  { key: 'returns', label: 'Returns' },
  { key: 'commerce', label: 'Commerce' },
  { key: 'payments', label: 'Payments' },
  { key: 'mobile', label: 'Mobile App' },
  { key: 'ops', label: 'Internal Ops' },
] as const;

export const F27M1_SENIOR = {
  label: 'Senior QA' as const,
  naLabel: 'N/A' as const,
} as const;

export const F27M1_PMSG = {
  label: 'Personal message (optional)' as const,
  rTag: 'Added to the invite email' as const,
  placeholder:
    "Add a note that appears at the top of the invite email (e.g., 'Welcome to QA Nexus — looking forward to working with you')" as const,
  charLimit: 500 as const,
} as const;

export const F27M1_RESEND = {
  leadPart: 'Resend free tier' as const,
  sent: '234' as const,
  total: '3,000' as const,
  emailsUsedThisMonth: 'emails used this month' as const,
  budget: '~12 emails/user/month budget' as const,
  metricsLink: 'View email metrics →' as const,
} as const;

export const F27M1_FOOTER = {
  sumL1Prefix: 'Sending' as const,
  sumL1Invites: 'invites' as const,
  sumL2Prefix: 'Invites expire in' as const,
  sumL2Days: 7 as const,
  sumL2Tail: 'days · invitees route to F06b → F07b / F07c / F07d' as const,
  cancel: 'Cancel' as const,
  send: 'Send invites' as const,
} as const;

// Role catalog — verbatim from canonical .applyall + per-row .rsel labels.
// "Admin role disabled in pickers" per the canonical HTML comment (line 14).
export type F27M1Role = 'engineer' | 'lead' | 'senior' | 'stakeholder';
export const F27M1_ROLES: ReadonlyArray<{ key: F27M1Role; label: string; cls: string }> = [
  { key: 'engineer', label: 'QA Engineer', cls: 'eng' },
  { key: 'lead', label: 'QA Lead', cls: 'lead' },
  { key: 'senior', label: 'Senior QA', cls: 'eng' },
  { key: 'stakeholder', label: 'Stakeholder', cls: 'stake' },
] as const;

// Initial sample invitees — match canonical avatars (S/M eng + V lead),
// using Iksula data canon for emails (CLAUDE.md Iksula data canon).
// CloudFlare-protected emails in canonical were unreadable, replaced with
// plausible Iksula domain placeholders so the demo onboard flow works.
export type F27M1Invitee = {
  id: string;
  email: string;
  initial: string;
  avatarColor: 'eng' | 'lead' | 'admin' | 'stake';
  role: F27M1Role;
  projects: string[];
  projectMore?: number;
  seniorQa: boolean;
  seniorNA: boolean;
};
export const F27M1_INITIAL_INVITEES: ReadonlyArray<F27M1Invitee> = [
  {
    id: 'inv-1',
    email: 's.iyer@iksula.com',
    initial: 'S',
    avatarColor: 'eng',
    role: 'engineer',
    projects: ['Returns'],
    seniorQa: true,
    seniorNA: false,
  },
  {
    id: 'inv-2',
    email: 'm.kapoor@iksula.com',
    initial: 'M',
    avatarColor: 'eng',
    role: 'engineer',
    projects: ['Returns', 'Commerce'],
    seniorQa: false,
    seniorNA: false,
  },
  {
    id: 'inv-3',
    email: 'v.shah@iksula.com',
    initial: 'V',
    avatarColor: 'lead',
    role: 'lead',
    projects: ['Returns', 'Commerce'],
    projectMore: 1,
    seniorQa: false,
    seniorNA: true,
  },
];

/**
 * Add semantically-named exports below as the React port consumes
 * verbatim text from F27M1_RAW. Examples:
 *
 *   export const F27M1_RIGHT_RAIL_LABELS = F27M1_RAW.textByTag.span.slice(0, 8);
 *   export const F27M1_DEFECT_IDS = F27M1_RAW.ids.defectIds;
 *   export const F27M1_HEADINGS = F27M1_RAW.headings;
 */
