// Auto-generated by scripts/extract-canned-data.mjs
// Source HTML: /Users/yogeshmohite/AI_Tester_Project/Project10-QA_Nexus-frontend/QA Nexus/PM1/PM1_UI_v2/Redesign Frame by claude design/F27m1 Invite User Modal v2.html
// Frame: F27M1
// Generated: 2026-06-02T13:42:52.170Z
//
// Hard Rule 17 (CLAUDE.md): ALL text content in the React port for this
// frame MUST come from this file. ANY string in a component file that
// doesn't trace back to the v2 HTML is a Hard Rule 17 violation →
// visual gate FAIL.
//
// This file is intended as a STARTING POINT — the FE+1 dev should
// organize these raw extracts into semantically named exports
// (e.g. DEFECT_TITLES, CLUSTER_HEADINGS, RIGHT_RAIL_LABELS) that the
// React port imports from. Re-run this script to refresh extracts; do
// NOT hand-edit the RAW block (it'll be overwritten).

export const F27M1_RAW = {
  pageTitle: 'QA Nexus — F27m1 Invite to QA Nexus',
  headings: {
    h1: [],
    h2: [],
    h3: [],
    h4: [],
    h5: [],
    h6: [],
  },
  dataAttrs: {
    'screen-label': ['F27m1 Invite to QA Nexus'],
    cfemail: [
      '8ffceee1e5eef6a1e8fafffbeecfe6e4fcfae3eea1ece0e2',
      'caa7afafa4abe4b8aba58aa3a1b9bfa6abe4a9a5a7',
      '9ceaf5f7eefdf1b2f2fdf5eedcf5f7efe9f0fdb2fff3f1',
      '6211030c08031b4c0517121603220b0911170e034c010d0f',
      '3c515959525d124e5d537c55574f49505d125f5351',
      '0f7966647d6e6221616e667d4f66647c7a636e216c6062',
    ],
  },
  ids: {
    testCaseIds: [],
    defectIds: [],
    requirementIds: [],
    jiraTicketIds: [],
    importIds: ['#39', '#160'],
  },
  textByTag: {
    span: [
      'Invite to QA Nexus',
      'Send invites to join Iksula Services Pvt Ltd — they&#39;ll receive a Resend email with a set-password link.',
      'F27m1',
      'Workspace',
      'Iksula Services Pvt Ltd',
      'Email(s) *',
      'S',
      '[email&#160;protected]',
      'M',
      'V',
      'Apply to all:',
      'Returns',
      'Commerce',
      '+1',
      'Personal message (optional)',
      'Added to the invite email',
      '0 / 500',
      'Resend free tier · 234 / 3,000 emails used this month · ~12 emails/user/month budget',
      'Sending 3 invites · 2 QA Engineers, 1 Lead',
      'Invites expire in 7 days · invitees route to F06b → F07b / F07c / F07d',
      '3',
    ],
    div: [
      'Invite to QA Nexus Send invites to join Iksula Services Pvt Ltd — they&#39;ll receive a Resend email with a set-password link.',
      'Workspace Iksula Services Pvt Ltd',
      'You have 4 of 25 invite slots remaining this month',
      'Email(s) * S [email&#160;protected] M [email&#160;protected] V [email&#160;protected]',
      'Paste multiple emails separated by comma or newline. Max 25 per invite.',
      'Apply to all: QA Engineer Returns, Commerce Apply to all 3 emails',
      'S [email&#160;protected]',
      'Returns',
      'M [email&#160;protected]',
      'Returns Commerce',
      'V [email&#160;protected]',
      'Returns Commerce +1',
      'Personal message (optional) Added to the invite email',
      '0 / 500',
      'Resend free tier · 234 / 3,000 emails used this month · ~12 emails/user/month budget View email metrics →',
      'Sending 3 invites · 2 QA Engineers, 1 Lead Invites expire in 7 days · invitees route to F06b → F07b / F07c / F07d',
      'Cancel Send invites 3',
    ],
    p: [],
    li: [],
    a: ['[email&#160;protected]', 'View email metrics →'],
    button: [
      'QA Engineer',
      'Returns, Commerce',
      'Apply to all 3 emails',
      'QA Lead',
      'Cancel',
      'Send invites 3',
    ],
    label: ['Senior QA', 'N/A'],
    td: [],
    th: [],
    small: [],
    em: [],
    strong: [],
    b: ['4', '25', '234 / 3,000', '3', '2', '1', '7'],
    i: [],
    code: [],
  },
  images: {
    alts: [],
    srcs: [],
  },
  ariaAndTitle: {
    arias: ['Close', 'Remove'],
    titles: [],
  },
} as const;

/**
 * Page-level metadata extracted from the canonical v2 HTML <title> +
 * the first <h1>. Always safe to import directly.
 */
export const F27M1_PAGE_TITLE = 'QA Nexus — F27m1 Invite to QA Nexus' as const;

/**
 * Add semantically-named exports below as the React port consumes
 * verbatim text from F27M1_RAW. Examples:
 *
 *   export const F27M1_RIGHT_RAIL_LABELS = F27M1_RAW.textByTag.span.slice(0, 8);
 *   export const F27M1_DEFECT_IDS = F27M1_RAW.ids.defectIds;
 *   export const F27M1_HEADINGS = F27M1_RAW.headings;
 */
