// Auto-generated by scripts/extract-canned-data.mjs
// Source HTML: /Users/yogeshmohite/AI_Tester_Project/Project10-QA_Nexus-frontend/QA Nexus/PM1/PM1_UI_v2/Redesign Frame by claude design/F26m1 LLM Provider Setup Modal v2.html
// Frame: F26M1
// Generated: 2026-06-02T13:42:46.706Z
//
// Hard Rule 17 (CLAUDE.md): ALL text content in the React port for this
// frame MUST come from this file. ANY string in a component file that
// doesn't trace back to the v2 HTML is a Hard Rule 17 violation →
// visual gate FAIL.
//
// This file is intended as a STARTING POINT — the FE+1 dev should
// organize these raw extracts into semantically named exports
// (e.g. DEFECT_TITLES, CLUSTER_HEADINGS, RIGHT_RAIL_LABELS) that the
// React port imports from. Re-run this script to refresh extracts; do
// NOT hand-edit the RAW block (it'll be overwritten).

export const F26M1_RAW = {
  pageTitle: 'QA Nexus — Configure LLM Provider · F26m1 v2',
  headings: {
    h1: [],
    h2: [],
    h3: [],
    h4: [],
    h5: [],
    h6: [],
  },
  dataAttrs: {
    mode: ['fresh'],
    'screen-label': ['F26m1 Configure LLM Provider v2'],
    demo: ['fresh', 'edit'],
    step: ['1', '2', '3', '4'],
    prov: ['groq', 'gemini', 'custom'],
    a: ['composer', 'curator', 'sherlock'],
  },
  ids: {
    testCaseIds: [],
    defectIds: [],
    requirementIds: [],
    jiraTicketIds: [],
    importIds: [],
  },
  textByTag: {
    span: [
      'Demo',
      'Configure LLM Provider',
      'Set up Groq, Gemini, or a custom provider for Composer ⓘ + Sherlock ⓘ agents',
      'Last successful test: 2m ago at 12:30 IST · 47ms latency',
      '1',
      'Choose your provider',
      'OpenAI-compatible',
      'Groq',
      'gpt-oss-120b',
      '★ Recommended',
      'Free · 1,000 RPD',
      'Google Gemini',
      'Free · 1,500 RPD',
      'Custom Provider',
      '⚙ Advanced',
      '2',
      'Enter API key',
      '*',
      'Show',
      'Get your API key from console.groq.com/keys ›',
      '3',
      'Pick your primary model',
      'Recommended: openai/gpt-oss-120b — best quality + 500 tok/s + 131K context.',
      "Refer to your provider's docs for the exact model identifier string.",
      '4',
      'Advanced Optional',
      'defaults shown',
      'Must support the OpenAI-compatible chat-completions schema.',
      '0.4',
      '0.40',
      'Lower = deterministic. Raise for creative test cases.',
      'Per response cap. Sherlock RCAs may need 2,500+.',
      'Retries fail-over to Gemini 2.5 Flash on exhaustion.',
      'Streamed tokens render live in Composer + Sherlock.',
      'Each agent uses this provider unless overridden. Curator runs entirely on internal pgvector.',
      'Composer A1',
      'Uses primary provider',
      'Curator A2',
      'N/A — internal pgvector embeddings',
      'Sherlock A4',
      'Test connection',
      'POST /api/integrations/llm/test-connection — verifies key, model, latency. Test does not save.',
      'Save configuration Run Test connection first to verify before saving.',
      'Saved',
    ],
    div: [
      'Demo Fresh setup Edit existing',
      'Configure LLM Provider Set up Groq, Gemini, or a custom provider for Composer ⓘ + Sherlock ⓘ agents',
      'Editing existing configuration: Groq · openai/gpt-oss-120b Last successful test: 2m ago at 12:30 IST · 47ms latency',
      '1 Choose your provider',
      'Groq',
      '★ Recommended Free · 1,000 RPD',
      'Google Gemini',
      'Free · 1,500 RPD',
      'Custom Provider',
      '⚙ Advanced',
      '2 Enter API key',
      'API key * Show Replace',
      '3 Pick your primary model',
      'Primary model *',
      "Model identifier * Refer to your provider's docs for the exact model identifier string.",
      '4 Advanced Optional',
      'Endpoint URL * Must support the OpenAI-compatible chat-completions schema.',
      'Temperature 0.4 0.40',
      'Max tokens Per response cap. Sherlock RCAs may need 2,500+.',
      'Retry attempts Retries fail-over to Gemini 2.5 Flash on exhaustion.',
      'Streaming Enabled (recommended) Disabled',
      'Per-agent override Each agent uses this provider unless overridden. Curator runs entirely on internal pgvector. Composer A1',
      'Same as primary Override → Gemini 2.5 Flash Override → Custom endpoint',
      'Curator A2',
      'No LLM provider used',
      'Sherlock A4',
      'Test connection POST /api/integrations/llm/test-connection — verifies key, model, latency. Test does not save.',
    ],
    p: [
      'All three are OpenAI-compatible . Groq is recommended for speed and a generous free tier.',
      'Fastest inference — 500 tok/s on gpt-oss-120b .',
      'Reliable fallback — Gemini 2.5 Flash with long context.',
      'Any OpenAI-compatible endpoint — Anthropic, Together AI, self-hosted.',
    ],
    li: [],
    a: ['console.groq.com/keys ›'],
    button: [
      'Fresh setup',
      'Edit existing',
      'Reset & choose again',
      'Show',
      'Replace',
      'Test connection',
      'Cancel',
      'Save configuration',
    ],
    label: [
      'Groq Fastest inference — 500 tok/s on gpt-oss-120b . ★ Recommended Free · 1,000 RPD',
      'Google Gemini Reliable fallback — Gemini 2.5 Flash with long context. Free · 1,500 RPD',
      'Custom Provider Any OpenAI-compatible endpoint — Anthropic, Together AI, self-hosted. ⚙ Advanced',
      'API key *',
      'Primary model *',
      'Model identifier *',
      'Endpoint URL *',
      'Temperature 0.4',
      'Max tokens',
      'Retry attempts',
      'Streaming',
      'Per-agent override',
    ],
    td: [],
    th: [],
    small: [],
    em: [],
    strong: [],
    b: ['Groq · openai/gpt-oss-120b', 'openai/gpt-oss-120b', 'pgvector'],
    i: [],
    code: [],
  },
  images: {
    alts: [],
    srcs: [],
  },
  ariaAndTitle: {
    arias: ['Demo mode', 'Close', 'Show or hide key'],
    titles: [],
  },
} as const;

/**
 * Page-level metadata extracted from the canonical v2 HTML <title> +
 * the first <h1>. Always safe to import directly.
 */
export const F26M1_PAGE_TITLE = 'QA Nexus — Configure LLM Provider · F26m1 v2' as const;

/**
 * Add semantically-named exports below as the React port consumes
 * verbatim text from F26M1_RAW. Examples:
 *
 *   export const F26M1_RIGHT_RAIL_LABELS = F26M1_RAW.textByTag.span.slice(0, 8);
 *   export const F26M1_DEFECT_IDS = F26M1_RAW.ids.defectIds;
 *   export const F26M1_HEADINGS = F26M1_RAW.headings;
 */
